;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        electric-newline-and-maybe-indent
        haskell-indentation-delete-backward-char
        haskell-indentation-delete-char
        haskell-mode-contextual-space
        indent-for-tab-command
        kill-region
        ))

(setq mc/cmds-to-run-once
      '(
        ))
